In [6]:
!pip install numpy

You should consider upgrading via the 'C:\Users\Mohd Asif\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [47]:
import numpy as np

CONVERT [(1,2,3,4),(5,6,7,8),(9,10,11,12)] IN A 2D ARRAY OF 3,4

In [53]:
my_list =[(1,2,3,4),(5,6,7,8),(9,10,11,12)]
my_array = np.array(my_list)
print(my_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
arr = np.arange(1, 13).reshape(3, 4) 
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
arr.shape

(3, 4)

In [56]:
arr.ndim

2

In [57]:
arr.size

12

In [58]:
arr.dtype

dtype('int32')

 CREATE 2D ARRAY OF 20 ELEMENT

In [64]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
a=np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [30]:
b=np.arange(20).reshape(2,2,5)
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [68]:
c=np.arange(20).reshape(4,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
arr1.size
a.size
b.size
c.size

20

In [36]:
arr1.shape


(20,)

In [37]:
a.shape


(2, 10)

In [39]:
b.shape


(2, 2, 5)

In [40]:
c.shape

(4, 5)

In [16]:
arr1.ndim

1

In [17]:
arr1.dtype

dtype('int32')

CREATE  AN ARRAY FROM 10, 50 WITH A STEP OF 5 AND CONVERT TO 3 POSSIBLE ARRAY SHAPE COMBINATIONS.

In [18]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
a=np.arange(10, 50, 5,).reshape(4,2)
a

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [21]:
a=np.arange(10, 50, 5,).reshape(2,2,2)
a

array([[[10, 15],
        [20, 25]],

       [[30, 35],
        [40, 45]]])

In [29]:
a.size

8

In [30]:
a.shape

(8,)