In [14]:
!pip install numpy

You should consider upgrading via the 'C:\Users\Mohd Asif\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [16]:
import numpy as np

In [17]:
l1 = [2, 3, 54, 7]
np.array(l1)

array([ 2,  3, 54,  7])

In [6]:
arr1 = np.array(l1)

In [7]:
l2 = [2, 3, 54.43, 7.12]
np.array(l2)

array([ 2.  ,  3.  , 54.43,  7.12])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
np.arange(10.5, 20.5, 1.5)

array([10.5, 12. , 13.5, 15. , 16.5, 18. , 19.5])

In [10]:
np.arange(10.5, 20.5, 1.5, dtype='int')

array([10, 12, 14, 16, 18, 20, 22])

In [11]:
arr1.size

4

In [12]:
arr1.shape

(4,)

In [13]:
arr1.ndim

1

In [14]:
arr1.dtype

dtype('int32')

In [35]:
mat3=np.arange(5,50,5).reshape(3,3)

In [36]:
bool_arr=mat3% 10==0

In [37]:
mat3[bool_arr]

array([10, 20, 30, 40])

In [38]:
mat3*2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [39]:
mat4=np.arange(1,10).reshape((3,3))

In [40]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
mat4*mat3

array([[  5,  20,  45],
       [ 80, 125, 180],
       [245, 320, 405]])

In [43]:
mat3 @ mat4

array([[150, 180, 210],
       [330, 405, 480],
       [510, 630, 750]])

In [44]:
mat3.max()

45

In [45]:
mat3.min()
mat3.sum()

225

In [46]:
np.random.random((2,2))

array([[0.76214787, 0.29641698],
       [0.2256488 , 0.08972309]])

In [47]:
np.random.randint((1,6))

array([0, 5])

In [48]:
ultimate=np.arange(25).reshape(5,5)

In [49]:
ultimate

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
ultimate[2:5,2]

array([12, 17, 22])

In [6]:
import random

In [7]:
random.choice(['gta', 'resident evil 4', 'wot', 'super mario'])

'resident evil 4'

In [8]:
random.choices([ 'gta', 'resident evil 4', 'wot', 'super mario' ],k=1)

['super mario']

In [23]:
ultimatrix = np.arange(25).reshape((5, 5))

In [24]:
ultimatrix[1][2]

7

In [25]:
ultimatrix[0]

array([0, 1, 2, 3, 4])

In [26]:
ultimatrix[1, 1]

6

In [27]:
ultimatrix[ 1, 1:4 ]

array([6, 7, 8])

In [28]:
ultimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ultimatrix[2:5, 2]

array([12, 17, 22])

In [30]:
ultimatrix[2:5, 2]

array([12, 17, 22])

In [51]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.vstack( (mat3 , mat4) )

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [54]:
mat5 = np.arange(1, 7).reshape((2, 3))

In [55]:
mat5

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
np.vstack((mat4, mat5))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
np.hstack( (mat3, mat4) )

array([[ 5, 10, 15,  1,  2,  3],
       [20, 25, 30,  4,  5,  6],
       [35, 40, 45,  7,  8,  9]])

In [60]:
np.hstack( (mat4, mat5))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [61]:
mat6 = np.arange(1, 7).reshape((3, 2))

In [62]:
mat6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
np.hstack( (mat3, mat6) )

array([[ 5, 10, 15,  1,  2],
       [20, 25, 30,  3,  4],
       [35, 40, 45,  5,  6]])

# pandas library: